# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MVhwZPXRoYaQ99nJOk9pDVcz-8qym56X
"""

print("我的年紀是19歲")

year=19
print("我的年紀是",year,"歲")

year= input("請輸入你的年紀")
print("年紀為", year)

print("我的名字是蕭平楚")

name="蕭平楚"
print("我的名字是","蕭平楚")

name=input("請輸入你的名字")
print("我的名字是",name)

print("我的體重是55公斤")

weight=55
print("我的體重是",weight,"公斤")

weight=input("請輸入你的體重")
print("體重為",weight)

