# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8A6zJFnLyqlosOepqjiNBZMtHXHL8Ky
"""

座號=int(input('請輸入座號'))
組別=(座號-1)//5+1
print('組別為',組別)

r= float(input('請輸入圓的半徑:'))
import math
面積=math.pi*r*r
圓周長=2*math.pi*r
print('圓的面積為',面積)
print('員的周長為',圓周長)

攝氏溫度=float(input('請輸入攝氏溫度:'))
華氏溫度=攝氏溫度*9/5+32
print('華氏溫度為',華氏溫度)

