# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeEMSgEzu7Wbcug5FNDpbPrGIQMgFF6K
"""

#input
noodle=input("有麵嗎？（yes/no)")
sauce=input("有醬料嗎？(yes/no)")

#process
if noodle=="yes" and sauce=="yes":
    print("今晚吃義大利麵！")

#output



print("well done")

